# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: afd0021ca100107b4ba1d1da0e8bcf682696c4e53610841ed17c41fe34695a36147179f823689bf8c43fb1fdd2b8aa71ee3b43b597a784906a083091239936e1

test:
  secret_key_base: eeddb56f2da195534d6e0be9bec61f66b22993d767b57438e8374aed1abd891b29a5a46d9eba1aed35b1aa5652d60c5135e66bab5631e928bed86fd2cec75fde

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
